### ISSUE TITLE
不应该提供原子样式类

### ISSUE THREAD

**Issue by Justineo** [ecomfe/esf#12]
用预处理的一大原因就是 CSS 没有样式上的复用机制，我们在 Less 层把样式的复用、继承解决掉，最后输出的 className 应该是比较抽象的，和样式耦合很低的才对。`utils.less` 里的这些类很明显是违背语义和样式分离原则的，也让我们用 Less 来维护样式代码的意义大打折扣。框架自身要用的 util 都应该封装到 mixin 里面。

**Comment by otakustay** [comment]
我上几天尝试用的时候，还是看到有`ui-align-center`之类的class和mixin，我认为这些**必须**去掉，也许少写代码是能得到一些些微弱的好处，但对原则的违背却是巨大的损失

**Comment by Justineo** [comment]
期望样式全丢给 class 来引入我觉得是不合适的。预处理器的一大作用就是解决「CSS 缺乏良好的复用机制从而导致只能利用 HTML class 来进行复用」这个问题的。

既然用了 Less，就应该利用预处理器提供的这种额外的抽象能力，在样式层来解耦，比如提供*变量*、*mixin* 都是比较合适的做法。目前 `utils.less` 中输出了很多样式类甚至是原子样式类，为了一句简单的 CSS 声明就添加一个新的 class，这早就已经是被公认为不合适的做法。

**Comment by yankun01** [comment]
// 实现block居中
.ui-mh-auto 
// float
.ui-float-left
.ui-float-right 
.ui-float-none

// overflow options
.ui-overflow-hidden
.ui-overflow-auto
.ui-overflow-scroll

// widths
.ui-fit
.ui-half-width
.ui-full-width 

// display
.ui-inline
.ui-block
.ui-inline-block

// clear fix helper
.ui-clearfix
// disabled
.ui-disabled 

刚看了一下代码，里面util里面大概有这么多。 @Justineo @otakustay 看看哪些是咱们能够用得到的。
剩下的我们把他移除。

**Comment by otakustay** [comment]
看上去都应该作为mixin存在，不要以class的形式提供就OK了

对于那些只有一行CSS的，mixin大概也不需要了



Best regards

Gray Zhang



在 2015年2月10日 上午11:19:36, yankun01 (notifications@github.com) 写到:

// 实现block居中
.ui-mh-auto
// float
.ui-float-left
.ui-float-right
.ui-float-none

// overflow options
.ui-overflow-hidden
.ui-overflow-auto
.ui-overflow-scroll

// widths
.ui-fit
.ui-half-width
.ui-full-width

// display
.ui-inline
.ui-block
.ui-inline-block

// clear fix helper
.ui-clearfix
// disabled
.ui-disabled

刚看了一下代码，里面util里面大概有这么多。 @Justineo @otakustay 看看哪些是咱们能够用得到的。
剩下的我们把他移除。

**Comment by yankun01** [comment]
好了， util.less已经灰飞烟灭。
