### ISSUE TITLE
IE9,10下貌似看不到checkbox

### ISSUE THREAD

**Issue by beidoufe** [ecomfe/esf#17]
IE9,10下virtual的box挂了后，原生的checkbox貌似没有显示出来

**Comment by yankun01** [comment]
@beidoufe 你用的是哪个版本的。通过esui用的话需要加variant属性。 缺省的是没有自定义box的。

**Comment by beidoufe** [comment]
@yankun01  [demo](http://ecomfe.github.io/esf/demo/) 在IE9,10下打开，进入 `表单元素`- `checkbox` 看不到框框，我理解是该降级到原生的框框~

**Comment by yankun01** [comment]
这个是之前一个修改引起的，本来是针对IE8做的降级。 后来IE9-10居然也起作用了。 
在master分支上已经修改过了。 你再看看是不是能用。而且这次theme也做了调整。 准备择机发布beta。

@beidoufe

**Comment by beidoufe** [comment]
赞 ~\(≧▽≦)/~

**Comment by yankun01** [comment]
fixed in 1.0.0-alpha.9.
